### ISSUE TITLE
Configurations per bundle

### ISSUE THREAD

**Issue by cymen** [hsume2/browserify-rails#16]
The configuration PR are good however I need more control. From what I can tell from the browserify CLI, using options like `external` are per bundle. So I need a configuration method that lets me specify the options for each bundle. So that one bundle includes a module while for other bundles it is external.

**Comment by hsume2** [comment]
Could you provide an example of how you would want the `browserify` command to look? Thanks.

**Comment by cymen** [comment]
So on the Rails side, I'd like a configuration file (say `config/browserify.yml`) and in it, I could give command line options for specific files. If we take this example:

https://github.com/substack/node-browserify#multiple-bundles

I want to be able to say something like (going to use JS objects instead of YAML here for convenience):

```
...
  robot: {
    outfile: 'static/common'
  },
  beep: {
    external: ['static/common']
  },
  boop: {
    external: ['static/common']
  }
...
```

The root would be `app/assets/javascripts` for paths. Does that make sense?

I would also use this as an opt-in for browserify or at least make that an option (which is enabled by default). So instead of browserify running on everything and excluding vendor or other sources, we'd opt-in what we wanted browserified. That solves a lot of problems with JavaScript coming from gems, vendor, etc.

My working scenario is a Rails project that has a big chunk of JS that we want to modularize but also has a bunch of other page enhancement-type JS that is outside the scope and should stay as is. It also uses a number of gems for JavaScript and eventually we'd like to address that but on our own schedule instead of being forced. Right now, I have a hacked browserify-rails that excludes vendor, gems, jasmine, etc.

I am going to work on this right now. But any feedback or suggestions you have or observations on something I'm missing would be appreciated.

**Comment by cymen** [comment]
Translating it to YAML (without taking advantage of fancy features to avoid duplication), it would look something like:

```
strict: true
robot:
  outfile: common
beep:
  external:
    - robot
boop:
  external:
    - robot
```

I'm going to get this working using your example Rails 3.2 application to show how I want/need it to work. I'm using `strict` to indicate it should be opt-in instead of opt-out. `strict` is not very good at conveying this but I'll go with it for now. We just need something to toggle so the current example in the Rails app can continue to work.

**Comment by tylerball** [comment]
Unfortunate that this wasn't resolved. Bundle-specific configuration is essential to keeping the amount of javascript on a page small when including multiple bundles. Any other thoughts? Would you be open to having the work done in #17 merged if the code was up to your standards?

**Comment by cymen** [comment]
@tylerball I agree it is unfortunate. The fork is here:

https://github.com/browserify-rails/browserify-rails

I pushed a new version of the gem just now (0.4.1).

**Comment by martenlienen** [comment]
I did not forget about this, but currently I am busy preparing for exams.
