### ISSUE TITLE
Getting it to work with rake assets:precompile

### ISSUE THREAD

**Issue by the-swerve** [hsume2/browserify-rails#27]
Everything works great in my development mode without asset precompilation, but when I try to get it to work with `rake assets:precompile`, it gives me "require is not defined."

Could it have something to do with my config.assets.paths or my config.assets.precompile? Been at this for a long time now and no headway.

**Comment by martenlienen** [comment]
I am just precompiling my big project to check, but I have not had problems until now. Could you post your full error message?

**Comment by the-swerve** [comment]
Thanks for checking this out. Precompilation doesn't return any errors at all, but it doesn't seem like it's browserifying. The error I mentioned above is in the js: `Uncaught ReferenceError: require is not defined`

It might have something to do with my `config.assets.precompile` setting in `application.rb`. I have it set to precompile everything named "index.*". I've tried removing that config line, and I've also tried changing it to precompile all js files. Had no luck with either change.

I'll go into the postprocessor code and add a bunch of log messages to see if I can tell what it's doing.

**Comment by the-swerve** [comment]
I've had no luck. I ended up removing the gem and browserifying everything manually. The gem works in development mode without precompilation, but if I precompile the assets, nothing is browserified. 

Like I said, I'm just running browserify myself now, so feel free to close this if you think it's just user error somehow.

**Comment by martenlienen** [comment]
I am sorry. I am using browserify-rails in production and everything works fine.

So I will close this as I see no chance of fixing it without your help. Thanks for your participation.
