### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by rymohr** [hsume2/browserify-rails#31]
Just noticed that ownership of this gem has been transferred to https://github.com/browserify-rails/browserify-rails

Might want to make a note of it in the description.

**Comment by martenlienen** [comment]
That's a bit of an open issue. It was/is more of a hostile takeover. (Yes, he has the gem. Things are/were weird). Development continues here, too, and I am currently refactoring the source to take care of some of the issues. I will also push this version to rubygems.

**Comment by rymohr** [comment]
Sorry, I assumed since he had the gem he had permission.  Always unfortunate when you see an active split like this.

**Comment by rymohr** [comment]
Cymen invited me to join the browserify-rails org over the weekend.  With ownership of the org and gem I expect to see development naturally trend his way.  I hate to see two (nearly) identical forks in active development though.  Especially since this repo's owned by @hsume2 yet he doesn't appear to be actively involved anymore.

@cymen @CQQL any chance we can resolve the issues between you two and carry on development together at https://github.com/browserify-rails/browserify-rails?

**Comment by hsume2** [comment]
@rymohr since I'm not actively involved in browserify-rails anymore, I'm happy to leave this decision in the hands of you,@CQQL and @cymen. Ideally the two repos can be converged, or one of the two repos ought to be renamed.

**Comment by cymen** [comment]
@CQQL I had the same experience that things were very weird. Is it possible for you to see that my experience was at least as weird as yours? And what you find weird was my reaction to how you handled my PR?

You have to understand what you see as hostile from my side I experience just as much from your side. I mulled over the gem name but since I brought it to the table, I felt in the end it was my right to take it away from the table if I was being asked to leave.

**Comment by martenlienen** [comment]
I think, we could continue development all together on browserify-rails/browserify-rails. I will verify, that everything still works on my project with version 0.4.1 from rubygems and then update the readme etc. to point to the new repository. 

I would like to receive push access on the organization. It will probably elapse some time until I find time to work on browserify-rails again, but then I would like to improve the test suite and do some refactoring.

And yes, we had a communication problem, but now everyone has cooled off and I don't see a problem for further cooperation.

**Comment by cymen** [comment]
I've added you as an owner to the repo/organization and the gem too.

**Comment by martenlienen** [comment]
Okay, thanks. I will do the other things this weekend.

**Comment by cymen** [comment]
@CQQL I wanted to say a couple things:

1) I'll work very hard on communication and be careful not to take offense. I did overreact.
2) I will not change your access to the git repo (I gave you owner on everything to reflect that).
3) I will not change your access to the gem (you have owner on that too).

**Comment by rymohr** [comment]
Thanks guys.  I'll move the two issues I opened yesterday over to the new repo.

**Comment by martenlienen** [comment]
I updated our main project to the latest version and linked to the new repository in the readme.

@hsume2 Could you please update the repository description with a link to the new repository?

**Comment by hsume2** [comment]
@CQQL sure thing. I've updated the repository description.

**Comment by martenlienen** [comment]
Thanks
