### ISSUE TITLE
Recompilation in development

### ISSUE THREAD

**Issue by callum** [hsume2/browserify-rails#4]
I've found that I have to make a small change to my `application.js` file any time I make a change to a required module to trigger recompilation when I reload in the browser. Why is this? How do gems like https://github.com/rails/sass-rails handle this?

**Comment by metaskills** [comment]
Would something like this help?

**Do Not Cache Rails/Sprockets Assets In Development**
https://gist.github.com/metaskills/9028312

**Comment by hsume2** [comment]
@callum you're right, `application.js` isn't regenerating because we're not using sprockets directives `//=require ./foo`. Because of that, Sprockets doesn't know it needs to regenerate `application.js` when `foo.js` changes. I'll look into a fix for that. Stay tuned!

**Comment by hsume2** [comment]
@callum @metaskills thanks for the help. I've merged in a fix for this issue. Now, whenever a dependent file is changed, `application.js` will recompile.

**Comment by callum** [comment]
This is great. Glad you were able to look into it. I've just updated my fork (https://github.com/madebymany/browserify-rails) with your changes. Seems the dependencies aren't resolving correctly now:

```
couldn't find file './bigbird.js'
  (in /Users/callum/projects/***/app/assets/javascripts/application.js)
```

``` js
// application.js

"use strict";

var $ = require("jquery");
var BigBird = require("bigbird");
var Modal = require("./modal");
```

This may be an issue with https://github.com/thlorenz/browserify-shim. Strangely I'm having issues with all of my assets. Sass throws:

```
undefined method `environment' for nil:NilClass
  (in /Users/callum/projects/***/app/assets/stylesheets/application.scss)
```

What do you think @hsume2?
