### ISSUE TITLE
Gem on rubygems.org is outdated

### ISSUE THREAD

**Issue by martenlienen** [hsume2/browserify-rails#7]
Hi,
the [`browserify-rails` gem on rubygems.org](https://rubygems.org/gems/browserify-rails) is quite outdated. Will it be updated? For now I will depend on the git repository.

Thanks,
Marten

**Comment by hsume2** [comment]
Hi,

Incidentally, the  [`browserify-rails` gem on rubygems.org](https://rubygems.org/gems/browserify-rails) is a different gem, maintained by someone else.

I've pushed the most recent version of my gem to rubygems. [`hsume2-browserify-rails`](https://rubygems.org/gems/hsume2-browserify-rails). This way you don't have to depend on the git repository. :)

Thanks,
Henry
